name: transforma_dados
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pandas=2.0.3
  - tabula-py=2.0.1
  - pdfplumber=0.10.0
  - jpype1=1.4.1
  - pip=23.2.1
  - pip:
    - cryptography>=41.0.3